
### TEST GENERICO
GET  http://localhost:8080/cgi-bin/test.py/usuarios/5?formato=xml HTTP/1.1

### TESG cgi
GET  http://localhost:8080/cgi-bin/tester.py

### test full cgi
GET http://localhost:8080/cgi-bin/test_cgi.py

### Solicitud POST para enviar datos al script CGI
POST http://localhost:8080/cgi-bin/test-post.py
Content-Type: application/json

{
    "accion": "procesar_pedido",
    "id_usuario": 12345,
    "productos": [
        {
            "nombre": "Laptop",
            "cantidad": 1,
            "precio": 999.99
        },
    ],
    "nota_adicional": "Entrega urgente requerida."
}