
###
GET  http://localhost:8090


### test redirection
GET http://localhost:8080//allurl/

###
GET  http://localhost:8080

###
GET  http://localhost:8070

### test full cgi
GET http://localhost:8080/cgi-bin/test_cgi.py

### Solicitud POST para enviar datos al script CGI
POST http://localhost:8080/cgi-bin/test-post.py
Content-Type: application/json
Content-Length: 261

{
    "accion": "procesar_pedido",
    "id_usuario": 12345,
    "productos": [
        {
            "nombre": "Laptop",
            "cantidad": 1,
            "precio": 999.99
        }
    ],
    "nota_adicional": "Entrega urgente requerida."
}